### ISSUE TITLE
Rounding 

### ISSUE THREAD

**Issue by amrit-hx** [BenjaminVanRyseghem/numbro#333]
Hi,

I can't find any examples which will round a number to the nearest integer. The format '0,0' displays any all decimals from the number being formatted. 

Any help appreciated

**Comment by BenjaminVanRyseghem** [comment]
```js
numbro(12.3).format("0a")
// -> "12"
numbro(12.6).format("0a")
// -> "13"
```

Is it what you are looking for?

**Comment by amrit-hx** [comment]
Yes it is, many thanks.

**Comment by eriksteinebach** [comment]
I am having the same question, but "a" doesn't solve my problem, because it also makes thousands into 1k. This behavior changed in v2 right? Although it is probably a good change, I am looking for the ability to format the value to remove the decimals, but keep the thousands (the original v1.x behavior). Something like:
123,123.34 => 123,123
123000.3432 => 123,000

I could probably cast the source value to an int, but we are formatting based on a setting in our CMS, so I would prefer the format to define that we don't want to see any decimals (and round to an int).

Which format string should I use in that case?

Thank you!

**Comment by BenjaminVanRyseghem** [comment]
```js
numbro(132324.52345).format({mantissa:0})
//>"132325"
```

Is it what you are looking for?

**Comment by eriksteinebach** [comment]
Right, that would probably work. My problem with that is that we show the formats in our CMS (through a selection dropdown). Our content editor selects the correct format. We could definitely define our own format (and under the covers use the above solution), but it would be ideal if I could define is at a standard format string. Does that make sense?

**Comment by BenjaminVanRyseghem** [comment]
I see your issue. Unfortunately, there is no string representation matching this use case (thus the introduction of a literal object).

If I were you, my approach would be to show a description of the format in the dropdown, like:

```js
let options = [
    {
        name: "No mantissa",
        value: { mantissa: 0 }
    },
    {
        name: "Thousand separated",
        value: { thousandSeparated: true }
    }
]
```

Idk if that makes sense to you though :smile:

**Comment by eriksteinebach** [comment]
I understand. I just wanted to be sure. Because this was the default behavior in v1.x and a breaking change for v2 I kind of expected a "simple" workaround/fix. No problem, thanks for the help

**Comment by BenjaminVanRyseghem** [comment]
Sorry, this one is kinda complicated as the previous behavior was "broken".
