### ISSUE TITLE
No version 2.0.6 on CDNJS or Minified files in Github Download

### ISSUE THREAD

**Issue by fearlex** [BenjaminVanRyseghem/numbro#356]
First of all, amazing job, the plugin is amazing.

Now, I'm trying to get the latest version 2.0.6, but it is not available on CDNJS, even when the official numbro website says it is. Last version on cdnjs is 2.0.5 which contains a bug that was fixed about decimal points not showing when no decimals added.

The Release tag download from here (Github), doesn't have the minified files.

I can minify it myself, that is not why i'm reporting this. Is just so the developer is aware, in case he isn't.

**Comment by BenjaminVanRyseghem** [comment]
thanks for the report. I have no clue why the CDNJS is not up to date, I will investigate :smile:

**Comment by fearlex** [comment]
Please let me know when is fixed as i’m currently using version 2.0.5 from the cdnjs, I was not able to minify the 2.0.6 version from github. It was giving me some Const error when trying to uglifyjs it.

**Comment by MartinKolarik** [comment]
You can get the minified file from https://cdn.jsdelivr.net/npm/numbro@2.0.6/dist/numbro.min.js, all npm packages are available there automatically.

**Comment by fearlex** [comment]
@MartinKolarik Thank you!

@BenjaminVanRyseghem Thank you too.

**Comment by rmesser** [comment]
I know this ticket is closed, but the same issue exists now with 2.10: the website says you can use a 2.1.0 link to cdnjs, but it doesn't work. 2.0.6 is the latest version on cdnjs as of today.

So maybe the website should suggest using cnd.jsdelivr.net if cdnjs doesn't have the latest. Otherwise people have to waste time searching for it.
