### ISSUE TITLE
update BigNumber

### ISSUE THREAD

**Issue by alumni** [BenjaminVanRyseghem/numbro#466]
There aren't any breaking changes in `bignumber 9.0`, in your dependencies you could add:
```
"dependencies": {
    "bignumber.js": "^8.1.1 || ^9.0.0"
}
```
It will help when `numbro` is used together with another library that depends on `bignumber`.

**Comment by BenjaminVanRyseghem** [comment]
Thanks, I'll investigate this asap :smile:

**Comment by amcclain** [comment]
Hi - bumping this ticket to see if it would be possible to reconsider this update.  We've been bitten by a very strange, low-level Chromium bug with their maglev compiler that breaks rounding. The maintainer of bignumber.js has released a workaround to the issue in a new 9.1.2 release, but numbro is still specifying 8.x

See https://github.com/MikeMcl/bignumber.js/issues/354 for the issue and discussion within the BigNumber project. 

Note again this is not a bug with their library - it's a Chromium bug and the fix is already underway - but it highlights how helpful it would be to have this one dependency updated in numbro.  

The changelog entry for the bignumber 9.x major release isn't too clear (has compatibility with legacy browsers been _improved_ or removed?), but it does not look like the API itself changed: https://github.com/MikeMcl/bignumber.js/blob/master/CHANGELOG.md#900

**Comment by BenjaminVanRyseghem** [comment]
https://github.com/BenjaminVanRyseghem/numbro/pull/679

**Comment by amcclain** [comment]
Appreciate it! Will keep an eye out for a merge/release - hoping this could make it into a 2.3.7 or 2.4.0 release soon?

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.4.0 :smile:
