### ISSUE TITLE
Format issue with average

### ISSUE THREAD

**Issue by Isha-Sharma** [BenjaminVanRyseghem/numbro#546]
Input: 999999
Format: {average: true}
Output: 1000k
Expected Output: 1m

Likewise, it's happening for all the corner cases.

Appreciate if someone could help me with this.

**Comment by BenjaminVanRyseghem** [comment]
@all-contributors please add @Isha-Sharma  for bug

**Comment by BenjaminVanRyseghem** [comment]
Fixed in `develop`

**Comment by Isha-Sharma** [comment]
Thanks @BenjaminVanRyseghem  for the prompt response :)

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.3.0

**Comment by BenjaminVanRyseghem** [comment]
I changed a bit the interface to prevent losing a feature.

Often, when formatting currency, it's convenient to have more info, hence formatting `999 999 -> 1000k`. On the other hand, when formatting numbers (as the number of attendants to an event), such precision is often useless, and we would prefer `999 999 -> 1m`.

To allow such a behavior, I introduced `lowPrecision: Boolean` with the following behavior:
- when `true`, it will always format as `1m`
- when `false`, it will always format as `1000k`
- when `undefined`, it will be `true` when formatting currency, `false` otherwise

**Comment by hafezdivandari** [comment]
@BenjaminVanRyseghem 

> * when `true`, it will always format as `1m`
> * when `false`, it will always format as `1000k`
> * when `undefined`, it will be `true` when formatting currency, `false` otherwise

But when `lowPrecision` is undefined, it will be `false` when formatting currency, `true` otherwise
```js
numbro(999999).format({average:true, lowPrecision: false}); // "1000k"
numbro(999999).format({average:true, lowPrecision: true});  // "1m"
numbro(999999).format({average:true});                      // "1m"
numbro(999999).format({average:true, output: 'currency'});  // "$1000k"
```

The problem:
```js
numbro(60).format({average:true});        // "60"
numbro(600).format({average:true});       // "1k" expected "600"
numbro(6000).format({average:true});      // "6k"
numbro(60000).format({average:true});     // "60k"
numbro(600000).format({average:true});    // "1m" expected "600k"
numbro(6000000).format({average:true});   // "6m"
numbro(60000000).format({average:true});  // "60m"
numbro(600000000).format({average:true}); // "1b" expected "600m"
```
How to achieve these expected outputs?

**Comment by sammarks** [comment]
I think this was a breaking change; I get format errors now whenever using `formatCurrency()` without specifying `average`. It seems it injects `lowPrecision` in there regardless of if `average` is currently being used or not.
